/*
 * Open Service Broker API
 *
 * The Open Service Broker API defines an HTTP(S) interface between Platforms and Service Brokers.
 *
 * The version of the OpenAPI document: master - might contain changes that are not yet released
 * Contact: open-service-broker-api@googlegroups.com
 * Generated by: https://openapi-generator.tech
 */

/// Error : See [Service Broker Errors](https://github.com/openservicebrokerapi/servicebroker/blob/master/spec.md#service-broker-errors) for more details.

#[derive(Debug, PartialEq, Serialize, Deserialize)]
pub struct Error {
    #[serde(rename = "error", skip_serializing_if = "Option::is_none")]
    pub error: Option<String>,
    #[serde(rename = "description", skip_serializing_if = "Option::is_none")]
    pub description: Option<String>,
    #[serde(rename = "instance_usable", skip_serializing_if = "Option::is_none")]
    pub instance_usable: Option<bool>,
    #[serde(rename = "update_repeatable", skip_serializing_if = "Option::is_none")]
    pub update_repeatable: Option<bool>,
}

impl Error {
    /// See [Service Broker Errors](https://github.com/openservicebrokerapi/servicebroker/blob/master/spec.md#service-broker-errors) for more details.
    pub fn new() -> Error {
        Error {
            error: None,
            description: None,
            instance_usable: None,
            update_repeatable: None,
        }
    }
}
