/*
 * Open Service Broker API
 *
 * The Open Service Broker API defines an HTTP(S) interface between Platforms and Service Brokers.
 *
 * The version of the OpenAPI document: master - might contain changes that are not yet released
 * Contact: open-service-broker-api@googlegroups.com
 * Generated by: https://openapi-generator.tech
 */

#[derive(Debug, PartialEq, Serialize, Deserialize)]
pub struct MaintenanceInfo {
    #[serde(rename = "version")]
    pub version: String,
    #[serde(rename = "description", skip_serializing_if = "Option::is_none")]
    pub description: Option<String>,
}

impl MaintenanceInfo {
    pub fn new(version: String) -> MaintenanceInfo {
        MaintenanceInfo {
            version: version,
            description: None,
        }
    }
}
