/*
 * Open Service Broker API
 *
 * The Open Service Broker API defines an HTTP(S) interface between Platforms and Service Brokers.
 *
 * The version of the OpenAPI document: master - might contain changes that are not yet released
 * Contact: open-service-broker-api@googlegroups.com
 * Generated by: https://openapi-generator.tech
 */

#[derive(Debug, PartialEq, Serialize, Deserialize)]
pub struct PositiveIntegerDefault0 {}

impl PositiveIntegerDefault0 {
    pub fn new() -> PositiveIntegerDefault0 {
        PositiveIntegerDefault0 {}
    }
}
