/*
 * Open Service Broker API
 *
 * The Open Service Broker API defines an HTTP(S) interface between Platforms and Service Brokers.
 *
 * The version of the OpenAPI document: master - might contain changes that are not yet released
 * Contact: open-service-broker-api@googlegroups.com
 * Generated by: https://openapi-generator.tech
 */

#[derive(Debug, PartialEq, Serialize, Deserialize)]
pub struct Schemas {
    #[serde(rename = "service_instance", skip_serializing_if = "Option::is_none")]
    pub service_instance: Option<crate::models::ServiceInstanceSchema>,
    #[serde(rename = "service_binding", skip_serializing_if = "Option::is_none")]
    pub service_binding: Option<crate::models::ServiceBindingSchema>,
}

impl Schemas {
    pub fn new() -> Schemas {
        Schemas {
            service_instance: None,
            service_binding: None,
        }
    }
}
