/*
 * Open Service Broker API
 *
 * The Open Service Broker API defines an HTTP(S) interface between Platforms and Service Brokers.
 *
 * The version of the OpenAPI document: master - might contain changes that are not yet released
 * Contact: open-service-broker-api@googlegroups.com
 * Generated by: https://openapi-generator.tech
 */

#[derive(Debug, PartialEq, Serialize, Deserialize)]
pub struct ServiceBindingVolumeMountDevice {
    #[serde(rename = "volume_id")]
    pub volume_id: String,
    #[serde(rename = "mount_config", skip_serializing_if = "Option::is_none")]
    pub mount_config: Option<serde_json::Value>,
}

impl ServiceBindingVolumeMountDevice {
    pub fn new(volume_id: String) -> ServiceBindingVolumeMountDevice {
        ServiceBindingVolumeMountDevice {
            volume_id: volume_id,
            mount_config: None,
        }
    }
}
