/*
 * Open Service Broker API
 *
 * The Open Service Broker API defines an HTTP(S) interface between Platforms and Service Brokers.
 *
 * The version of the OpenAPI document: master - might contain changes that are not yet released
 * Contact: open-service-broker-api@googlegroups.com
 * Generated by: https://openapi-generator.tech
 */

#[derive(Debug, PartialEq, Serialize, Deserialize)]
pub struct ServiceBindingEndpoint {
    #[serde(rename = "host")]
    pub host: String,
    #[serde(rename = "ports")]
    pub ports: Vec<String>,
    #[serde(rename = "protocol", skip_serializing_if = "Option::is_none")]
    pub protocol: Option<Protocol>,
}

impl ServiceBindingEndpoint {
    pub fn new(host: String, ports: Vec<String>) -> ServiceBindingEndpoint {
        ServiceBindingEndpoint {
            host: host,
            ports: ports,
            protocol: None,
        }
    }
}

///
#[derive(Debug, PartialEq, Serialize, Deserialize)]
pub enum Protocol {
    #[serde(rename = "tcp")]
    Tcp,
    #[serde(rename = "udp")]
    Udp,
    #[serde(rename = "all")]
    All,
}
