/*
 * Open Service Broker API
 *
 * The Open Service Broker API defines an HTTP(S) interface between Platforms and Service Brokers.
 *
 * The version of the OpenAPI document: master - might contain changes that are not yet released
 * Contact: open-service-broker-api@googlegroups.com
 * Generated by: https://openapi-generator.tech
 */

#[derive(Debug, PartialEq, Serialize, Deserialize)]
pub struct ServiceInstanceUpdateRequest {
    /// See [Context Conventions](https://github.com/openservicebrokerapi/servicebroker/blob/master/profile.md#context-object) for more details.
    #[serde(rename = "context", skip_serializing_if = "Option::is_none")]
    pub context: Option<serde_json::Value>,
    #[serde(rename = "service_id")]
    pub service_id: String,
    #[serde(rename = "plan_id", skip_serializing_if = "Option::is_none")]
    pub plan_id: Option<String>,
    #[serde(rename = "parameters", skip_serializing_if = "Option::is_none")]
    pub parameters: Option<serde_json::Value>,
    #[serde(rename = "previous_values", skip_serializing_if = "Option::is_none")]
    pub previous_values: Option<crate::models::ServiceInstancePreviousValues>,
}

impl ServiceInstanceUpdateRequest {
    pub fn new(service_id: String) -> ServiceInstanceUpdateRequest {
        ServiceInstanceUpdateRequest {
            context: None,
            service_id: service_id,
            plan_id: None,
            parameters: None,
            previous_values: None,
        }
    }
}
